name: Docker Pipeline

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASS
      - name: docker build
        run: |
          docker build . -t ghcr.io/bemoty/sharex-upload-server:latest
      - name: docker push
        run: |
          docker push ghcr.io/bemoty/sharex-upload-server:latest
